# Generated by Django 3.1.7 on 2021-02-25 20:52

import django.core.validators
from django.db import migrations, models
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('user_rank', models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('user_score', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('user_country', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Users',
                'ordering': ['-user_score'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_score'], name='pages_user_user_sc_eb3a50_idx'),
        ),
    ]
